### ISSUE TITLE
Document advanced usage

### ISSUE THREAD

**Issue by meyertee** [haithembelhaj/sass-inline-svg#1]
First of all, thanks for publishing sass-inline-svg, it's exactly what I was looking for!

It would be helpful to document the usage in the SCSS code, especially the option to replace parts of the SVG is hard to figure out but highly useful!

E.g.:

```
.icon {
    background-image: svg("icon.svg", (path: (fill: green)));
}
```

**Comment by haithembelhaj** [comment]
@meyertee thanks so much for your feedback. I kind of forgot about the missing docs. 
Glad to know that some people are using this :)

**Comment by meyertee** [comment]
Cool, thanks!
