### ISSUE TITLE
Update dependencies to address code-injection vulnerability

### ISSUE THREAD

**Issue by howardcox** [haithembelhaj/sass-inline-svg#13]
The most recent version of [svgo](https://github.com/svg/svgo) is 1.2.2, but this package requires `^0.6.6`.

This older versions of `svgo` is locked to an older version of `js-yaml` ~3.6.0

Which has two vulnerabilities reported against it:
- https://npmjs.com/advisories/788
- https://npmjs.com/advisories/813

These vulnerabilities were fixed in `js-yaml` >=3.13.1, which is also the minimum version which the latest version of `svgo` requires.

**Comment by mattleong** [comment]
Yes, please address.

**Comment by haithembelhaj** [comment]
Fixed in 1.2.3
