### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by unsafecode** [haithembelhaj/sass-inline-svg#4]
I noticed version bumped from `0.2.0` to `1.0.0` - which were the changes?

Can you add a __CHANGELOG.md__ file to track these?

**Comment by haithembelhaj** [comment]
Thank you for the advice. I will try to automate my commits in a **CHANGELOG.md**. 
The biggest change was the [node-sass major version update](https://github.com/haithembelhaj/sass-inline-svg/commit/2a6e6b868dd3e017abe24547967f4162b33ec687).
