### ISSUE TITLE
SVG converting not working with sailsJS

### ISSUE THREAD

**Issue by peterklein** [haithembelhaj/sass-inline-svg#5]
is it known that the SVG Converter does not run with sailsJS?

If yes, which solution can be used to get it work fine?

**Comment by haithembelhaj** [comment]
Hello Peter,

no I didn't know about that. I'm using sails for some projects currently and having no problem with that.
I just configured the grunt tasks of sails to meet my demands. For example I added a file `/tasks/config/sass.js` with this content
```js
const compass = require('sass-inline-svg')

module.exports = function(grunt) {

  grunt.config.set('sass', {
    options: {
      functions: {
        svg: inliner('./', [options])
      }
    },
    ...
  })

  grunt.loadNpmTasks('grunt-sass');
}

```

Hope this is helpful!

**Comment by haithembelhaj** [comment]
Closing this one for lack of interaction
