### ISSUE TITLE
Should not compress SVG in base64

### ISSUE THREAD

**Issue by n-chardon** [haithembelhaj/sass-inline-svg#6]
This article https://css-tricks.com/probably-dont-base64-svg/ suggests that base64 is not the appropriate method for compressing inline SVG. Would it be possible to switch to a simpler URL encoding, as suggested in the CSS tricks article ?

**Comment by haithembelhaj** [comment]
By reading the comments on that page I'm not totally convinced by the benefits of this approach. 
But hey if you want to contribute to this project, feel free to make a pull request and I will happily merge it. 

I could imagine this feature as an additional option like 
```js
{
 encodingFormat: 'uri' // defaults to 'base64'
}

``` 
The Filamentgroup lib for Grunticon uses this encoder https://github.com/filamentgroup/directory-encoder/blob/master/lib/svg-uri-encoder.js

This would be a great addition to the project :)
Thank you for this Feedback!
